### PR TITLE
Add support Symfony 5 for controller

### LINKED ISSUE #12797: Mautic 5 [beta 1] - SAML not working
### Mautic Version

5.0.x series

### PHP version

8.1

### What browsers are you seeing the problem on?

Not relevant

### What happened?

Hi everyone.
Today I did a clean install of Mautic v5[beta1], and unfortunately, login with the SAML provider doesn’t work.

Error log included.

Some steps to fix it?

Thanks!

### How can we reproduce this issue?

Step 1: Fill SAML settings fields, click to Save.
Step 2: Logout 
Step 3: Login with a SAML provider - Will getting error 500, with error above.

### Relevant log output

```shell
mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: “Attempted to load class “Controller” from namespace “Symfony\Bundle\FrameworkBundle\Controller”. Did you forget a “use” statement for another namespace?” at /var/www/html/vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php line 17 {“exception”:“[object] (Symfony\Component\ErrorHandler\Error\ClassNotFoundError(code: 0): Attempted to load class "Controller" from namespace "Symfony\Bundle\FrameworkBundle\Controller".\nDid you forget a "use" statement for another namespace? at /var/www/html/vendor/lightsaml/sp-bundle/src/LightSaml/SpBundle/Controller/DefaultController.php:17)”}
```

### Code of Conduct

- [X] I confirm that I have read and agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pasxel**
Fixing error on Mautic 5.0.0-alpha1 branch.

```
[Symfony\Component\ErrorHandler\Error\ClassNotFoundError]                                         
  Attempted to load class "Controller" from namespace "Symfony\Bundle\FrameworkBundle\Controller".  
  Did you forget a "use" statement for another namespace?
```

For reproducing just run `php bin/console debug:route` on branch 5.0.0-alpha1

### CODE REVIEW

**Comment by escopecz** [comment]
I can replicate.

Do you have some steps to test? I tried this:
1. Update the line in https://github.com/mautic/mautic/blob/5.x/app/composer.json#L122 to `"url": "https://github.com/pasxel/SpBundle.git"`
2. Run `composer update --lock` in the Mautic root dir

But it didn't update the package.

**Comment by patrykgruszka** [comment]
@pasxel please provide the steps how to test this PR

**Comment by pasxel** [comment]
To test I used: 
- Update the line in https://github.com/mautic/mautic/blob/5.x/app/composer.json#L122 to "url": "https://github.com/pasxel/SpBundle.git"
- Update the line in https://github.com/mautic/mautic/blob/5.x/composer.json#L104 to "url": "https://github.com/pasxel/SpBundle.git"
- Run composer update --lock in the app dir and project dir

It should update vendors.

**Comment by mollux** [comment]
@escopecz you need to update the repo override in the root `composer.json`, not in the `app/composer.json`. 
That will correctly pull from the wanted source

**Review by patrykgruszka — APPROVED** [review]
@pasxel I haven't been able to test this with your example. The composer probably pulled the changes from the master branch. I've replaced the code directly in the vendor and the command works after your changes:

```
ddev exec php bin/console debug:router                                                                                                                                                                                                                    
 -------------------------------------------- ---------------- -------- ------ ------------------------------------------------------------------------------------------------- 
  Name                                         Method           Scheme   Host   Path                                                                                             
 -------------------------------------------- ---------------- -------- ------ ------------------------------------------------------------------------------------------------- 
  _wdt                                         ANY              ANY      ANY    /_wdt/{token}                                                                                    
  _profiler_home                               ANY              ANY      ANY    /_profiler/     
...
```

**Review by mollux — APPROVED** [review]
fixes and improvements make sense, and they solve the issue!

**Comment by escopecz** [comment]
Thanks everyone! Is there anything blocking the merge?

**Comment by mollux** [comment]
@escopecz somehow i have no write access, so please go ahead merging :)

**Comment by petecodes123** [comment]
Hi all,

How can I resolve this issue with my current Mautic 5.0.3 installation ?

**Comment by escopecz** [comment]
@petecodes123 this was fixed in Mautic 5.0.3 with https://github.com/mautic/mautic/pull/13253. If you've installed Mautic with Composer, try to run `composer install`. It won't hurt to try that.

**Pull request merged**
